# Use an official Python runtime as a parent image
FROM python:3.9-slim

# Set the working directory in the container
WORKDIR /usr/src/app

# Copy the current directory contents into the container at /usr/src/app
COPY . .

# Install the required Python packages
RUN pip install --no-cache-dir aiocoap paho-mqtt plotly nicegui networkx

# Make the entry point script executable
RUN chmod +x entrypoint-ds.sh

# Run the entry point script
ENTRYPOINT ["./entrypoint-ds.sh"]